### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by jzting** [heestand-xyz/VertexKit#1]
Hi, I'd like to try out VertexKit but am having issues building.

When using:
`
  pod 'VertexKit'
`

I get:
`
Showing All Errors Only
/Users/jzting/Desktop/pixel/Pods/VertexKit/Source/3DPIX/ParticlesUV3DPIX.swift:40:51: Cannot use optional chaining on non-optional value of type 'PIX.Res'
`

When using:
`
  pod 'VertexKit', :git => 'https://github.com/hexagons/VertexKit', :branch => 'master'
`

I get:
`
Showing All Errors Only
/Users/jzting/Desktop/pixel/Pods/VertexKit/Source/3DEngine.swift:14:8: No such module 'LiveValues'
`

**Comment by heestand-xyz** [comment]
Hi, sorry I made a major refactor of the dependency PixelKit, will fix!

**Comment by heestand-xyz** [comment]
Now I've updated the pod, v0.3.0, let me know if it works for you!
If you have any questions regarding how to use VertexKit or PixelKit you can reach me at anton@hexagons.se

**Comment by heestand-xyz** [comment]
New docs for VertexKit and it's dependencies:
VertexKit: http://hexagons.se/vertex-kit/
PixelKit: http://pixelkit.net/docs/
RenderKit: http://renderkit.info
LiveValues: http://hexagons.se/live-values/

**Comment by jzting** [comment]
Thanks, that worked! I had to adjust the tutorial code to match the updated APIs.

**Comment by heestand-xyz** [comment]
Cool you got it to work! Sorry about the tutorial in the readme, it's updated now!
